[WiP] Selection of insertion entities from selected source list
thunder/custom_list pull request #7
Opened 2018-08-28 15:34 UTC by mtodor

2018-09-17 08:18 UTC, dbosen commented
fyi: i start reviewing this now

2018-09-17 08:42 UTC, dbosen commented
First functionality tests look good!

2018-09-18 11:07 UTC, dbosen requested changes

2018-09-18 11:07 UTC, dbosen commented on custom_list.info.yml
> +  - drupal:layout_builder
Why is this a dependency now?

2018-09-18 11:07 UTC, dbosen commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +    ];
This big configuration in code is not good (not just here, but in several places). Could that be stored in a real config file? Also, can it be simplified?  Especially the redundancies to the search_api SourceListPlugin should be minimized.

2018-09-18 11:07 UTC, dbosen commented on modules/custom_list_search_api/src/Plugin/SourceListPlugin/SearchApiSourceListPlugin.php
> +  ];
This is exactly the same as in DefaultSourceListPlugin, this could either be initialized in SourceListPluginBase or we make a config out of it. Or both.

2018-09-18 11:07 UTC, dbosen commented on modules/custom_list_search_api/src/Plugin/SourceListPlugin/SearchApiSourceListPlugin.php
> +  }
Same as comment to default list plugin.

2018-09-18 13:33 UTC, mtodor commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +    ];
We will do cleanup for this later - there are comments in code: `TODO: Heavy revisit and cleanup, how view config is generated.`

2018-09-18 13:38 UTC, mtodor commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +    ];
Issue created: 
https://www.drupal.org/project/custom_list/issues/3000596

2018-09-18 13:56 UTC, dbosen approved these changes

2018-09-18 14:00 UTC, merged