[WiP] Added filtering for default source list plugin
thunder/custom_list pull request #8
Opened 2018-09-14 12:15 UTC by mtodor

This branch uses PR #7 as base. So, it can be merged only when other PR is merged.

2018-09-18 14:43 UTC, dbosen commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +    if (method_exists($handler, 'operators')) {
I get a "Call to protected method Drupal\views\Plugin\views\filter\BooleanOperator::operators()" error, when filtering by default_langcode

2018-09-18 14:46 UTC, dbosen commented
Filtering by langcode does not seem to work, maybe I used the wrong value format? 
I tried several langcodes like en, de, fr. But I always got every article

2018-09-18 14:46 UTC, dbosen commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +    if (method_exists($handler, 'operators')) {
I get a "Call to protected method Drupal\views\Plugin\views\filter\BooleanOperator::operators()" error, when filtering by default_langcode

2018-09-18 15:18 UTC, dbosen commented on modules/custom_list_default/js/views/FilterForm.js
> +            filter_id: filter_id,
Would be nicer to display the filter name instead of the id

2018-09-18 15:56 UTC, dbosen requested changes

2018-09-18 15:56 UTC, dbosen commented on modules/custom_list_default/js/views/FilterList.js
> +      '  <div class="custom-list-default__filter-row__filter_id"><%= tplFilterSelector(filter_id) %></div>' +
Would be nicer to display the filter name instead of the id

2018-09-18 15:56 UTC, dbosen commented on modules/custom_list_default/js/views/FilterList.js
> +      '  <div class="custom-list-default__filter-row__value"><%- value %></div>' +
There are no indications of how a value should be formatted, and no validation seems to be done as well.
We have to improve this somehow, views seem to know how to display that better, maybe we can use something of it.

2018-09-18 15:56 UTC, dbosen commented on modules/custom_list_default/src/Plugin/SourceListPlugin/DefaultSourceListPlugin.php
> +        $filter_options[$option_id]['operators'] = $handler->operatorOptions();
We should not add options, that are not allowed, like type and status

2018-10-08 12:24 UTC, mtodor commented
@dbosen - related to langcode filtering. You have to ensure that you have enabled translation for that langcode, then you can use it for filtering. In other case it will be ignored.

2018-11-08 15:37 UTC, dbosen reviewed
Several filters are missing, that I can select in views ui. For example "Has taxonomy term"

2018-11-08 15:54 UTC, dbosen reviewed
When selecting "Moderation state" or "User has a revision" as filter, I cannot enter a value, but see the text "not available" in the input area

2018-11-21 12:21 UTC, dbosen commented on modules/custom_list_default/js/views/FilterList.js
> +      this.model.set({
Why not "me"?

2018-12-03 11:37 UTC, dbosen requested changes
For referenced taxonomies, there is a filter shown for the delta, but not for the tag itself.

2018-12-03 16:51 UTC, dbosen approved these changes

2018-12-04 09:02 UTC, merged